# .github/workflows/analyze-reports.yml
name: Network Analysis Scheduler

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
      APP_URL: ${{ secrets.APP_URL }}
      API_SECRET: ${{ secrets.API_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Analysis
        run: |
          curl -X POST "${{ secrets.APP_URL }}/api/analyze" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
            --fail

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Analysis Job Failed',
              body: `Analysis job failed at ${new Date().toISOString()}\nSee: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            })
